
sonar.projectKey=devops_final_fastapi
sonar.projectName=DevOps Final - FastAPI Service
sonar.projectVersion=1.0.0


sonar.sources=backend/app
sonar.tests=backend/tests

sonar.sourceEncoding=UTF-8
sonar.python.version=3.11, 3.12, 3.13

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/__pycache__/**,**/venv/**,**/*.pyc,**/test_results/**,backend/tests/**

sonar.qualitygate.wait=true
